### ISSUE TITLE
Hipster Ecommerce shop is broken

### ISSUE THREAD

**Issue by Frug** [elastic/synthetics-demo#21]
The e-commerce example URL is pointing to a shop hosted by vercel that is tied to different project now.

See https://github.com/elastic/synthetics-demo/blob/main/e-commerce/demo.journey.js#L3

**Comment by lucasfcosta** [comment]
Hi @Frug, thanks for the issue!

That domain name has become available and then someone linked it to a different project. The correct URL should be: https://elastic-synthetics-demo-ecommerce.vercel.app.
